server:
  port: 8000

eureka:
  instance:
    hostname: peer1
  client:
    # 在默认设置下，该服务注册中心也会将自己作为客户端来尝试注册它自己，所以我们需要禁用它的客户端注册行为
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://peer2:8001/eureka